apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: workshop-operator
  template:
    metadata:
      labels:
        name: workshop-operator
    spec:
      serviceAccountName: workshop-operator
      containers:
        - name: workshop-operator
          image: "quay.io/workspace7/workshop-operator:v0.0.1"
          command:
          - workshop-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "workshop-operator"
