// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/kameshs/v1alpha1.Workshop":       schema_pkg_apis_kameshs_v1alpha1_Workshop(ref),
		"./pkg/apis/kameshs/v1alpha1.WorkshopSpec":   schema_pkg_apis_kameshs_v1alpha1_WorkshopSpec(ref),
		"./pkg/apis/kameshs/v1alpha1.WorkshopStatus": schema_pkg_apis_kameshs_v1alpha1_WorkshopStatus(ref),
	}
}

func schema_pkg_apis_kameshs_v1alpha1_Workshop(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Workshop is the Schema for the workshops API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kameshs/v1alpha1.WorkshopSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kameshs/v1alpha1.WorkshopStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kameshs/v1alpha1.WorkshopSpec", "./pkg/apis/kameshs/v1alpha1.WorkshopStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kameshs_v1alpha1_WorkshopSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WorkshopSpec defines the desired state of Workshop",
				Properties: map[string]spec.Schema{
					"clean": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
					"openshiftAPIServer": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"project": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kameshs/v1alpha1.WorkshopProject"),
						},
					},
					"user": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kameshs/v1alpha1.WorkshopUser"),
						},
					},
					"stack": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kameshs/v1alpha1.WorkshopStack"),
						},
					},
				},
				Required: []string{"clean", "openshiftAPIServer", "project", "user", "stack"},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kameshs/v1alpha1.WorkshopProject", "./pkg/apis/kameshs/v1alpha1.WorkshopStack", "./pkg/apis/kameshs/v1alpha1.WorkshopUser"},
	}
}

func schema_pkg_apis_kameshs_v1alpha1_WorkshopStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WorkshopStatus defines the observed state of Workshop",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
